### ISSUE TITLE
Troddit

### ISSUE THREAD

**Issue by digitalblossom** [digitalblossom/alternative-frontends#22]
URL: https://www.troddit.com/

https://github.com/burhan-syed/troddit

**Comment by digitalblossom** [comment]
Added in #23

**Comment by FireMasterK** [comment]
This frontend seems to connect to Reddit directly too, for the API calls as well as images and videos. Maybe that should be included too

**Comment by digitalblossom** [comment]
> This frontend seems to connect to Reddit directly too, for the API calls as well as images and videos. Maybe that should be included too

Good catch, I'll add that
