### ISSUE TITLE
Onion Instance for Piped

### ISSUE THREAD

**Issue by FireMasterK** [digitalblossom/alternative-frontends#25]
This is the official onion instance for Piped, it's not documented. (yet)

http://piped2bbch4xslbl2ckr6k62q56kon56ffowxaqzy42ai22a4sash3ad.onion/

**Comment by FireMasterK** [comment]
The official instance is available via IPNS at ipns://piped-ipfs.kavin.rocks/

**Comment by digitalblossom** [comment]
Thanks, i added both in #27. As for the IPNS one, i hyperlinked it to your comment because github wouldn't let me do it with the ipns:// domain
