### ISSUE TITLE
Some early projects

### ISSUE THREAD

**Issue by throwaway-d** [digitalblossom/alternative-frontends#54]
You should wait until they are more matured and developed then add to this list.
1. URL: https://github.com/nesaku/BiblioReads
2. URL: https://github.com/rramiachraf/dumb
3. URL: https://codeberg.org/gothub/gothub

**Comment by NoPlagiarism** [comment]
Isn't 2 early 4 some of projects to even be in issue? GotHub not in alpha, It's only WIP now. But, let it be, I guess

**Comment by NoPlagiarism** [comment]
2. Dumb mentioned in #58

**Comment by digitalblossom** [comment]
Thanks for the suggestions!

Gothub is added f5588eda4b8cdc14da224b0017d9d43bb4d43c63
Dumb will be added
I'll look into BiblioReads
