### ISSUE TITLE
[MODIFY] Wikiless

### ISSUE THREAD

**Issue by privacytime101** [digitalblossom/alternative-frontends#55]
Wikiless as a project has been abandoned, though there was never any official word from the dev (Orenom). The repo is also nowhere to be found. Here's what I gathered from searching around briefly.

In early October, Codeberg moderation forced a private state on the Wikiless repo due to copyright issues raised by Wikimedia to Codeberg. Orenom then said publicly that they're working on removing the infringing content so Codeberg could bring it back up. October 17 is the last (that I found) of the dev being active, where they said that the timing was "literally the worst". 
The SSL certificate on Orenom's personal site expired yesterday. The main instance runs on Hetzner, which means they're still receiving monthly payments. 

I can't draw any conclusions as to what happened to Orenom (it's likely personal as well), but the listing should at least mention the state of the project. Either way, I don't see it getting any changes for the foreseeable future.

**Comment by NoPlagiarism** [comment]
Waiting for new, ha?

[https://orenom.fi/](https://orenom.fi/)

**Comment by privacytime101** [comment]
> Waiting for news, ha?
> 
> 
> 
> [https://orenom.fi/](https://orenom.fi/)

Yeah, that's what I checked as I was writing that

**Comment by NoPlagiarism** [comment]
> Yeah, that's what I checked as I was writing that

Left for others to check on news

**Comment by digitalblossom** [comment]
Added a notice to the Wikiless section and you to the credits at the top, thanks for taking the time to look into this :)
