### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by throwaway-d** [digitalblossom/alternative-frontends#56]
This is my preferred license https://creativecommons.org/publicdomain/zero/1.0/ when it comes to text.

**Comment by digitalblossom** [comment]
Added the GPLv3 license and added you to the credits at the top. Thanks!

**Comment by NoPlagiarism** [comment]
> added you to the credits at the top

Maybe `HexagonCDN` is more accurate, but `throwaway-d` works too, I guess :D

**Comment by throwaway-d** [comment]
I prefer `HexagonCDN` please :>

**Comment by digitalblossom** [comment]
> I prefer `HexagonCDN` please :>

https://github.com/digitalblossom/alternative-frontends/commit/91060a29998e7e5f79fd5bf52f1c9168abf74c35

Changed it 👍
