### ISSUE TITLE
[ADD] AnonymousOverflow

### ISSUE THREAD

**Issue by privacytime101** [digitalblossom/alternative-frontends#57]
Description: A privacy-friendly, no javascript alternative to StackOverflow.

Main instance: https://code.whatever.social

Repo: https://github.com/httpjamesm/AnonymousOverflow

Public instances: https://github.com/httpjamesm/AnonymousOverflow#clearnet-instances

Open-Source and Self-Hostable

**Comment by digitalblossom** [comment]
Added, thanks!
