### ISSUE TITLE
Anonymous Frontends 

### ISSUE THREAD

**Issue by danrobi11** [digitalblossom/alternative-frontends#6]
*I2P*
- http://tube.i2p/ ;; YouTube
- http://teddit.i2p/ ;; Reddit Reader 
- http://ramble.i2p/ ;; Ramble (Reddit-like)

*Tor*

- http://rambleeeqrhty6s5jgefdfdtc6tfgg4jj6svr4jpgk4wjtg3qshwbaad.onion/ ;; Ramble (Reddit-like) 

*Lokinet*

- http://invidious.loki/ or  http://f9whsuunmqfkf88f1pqhsjtbt6bhuq56bmdb5fq8mdiff8osfozo.loki/ ;; YouTube
- http://ramble.loki/ ;; Ramble (Reddit-like) Note: This service was down while posting this. 
- http://peertube.loki/ ;; PeerTube
- http://minecraft.loki/ ;; Minecraft server

**Comment by digitalblossom** [comment]
Thanks! I added the following:

- Teddit: I2P
- Invidious: I2P, Onion, Loki
