### ISSUE TITLE
UntrackMe android app to redirect

### ISSUE THREAD

**Issue by louis-bo** [digitalblossom/alternative-frontends#7]
URL: https://f-droid.org/packages/app.fedilab.nitterizeme/

URL: https://fedilab.app/wiki/untrackme/

UntrackMe once set by default to open Twitter, YouTube and Instagram links will transform them into Nitter, Invidious and Bibliogram links and delegate the action to another app.

**Comment by digitalblossom** [comment]
Thanks Louis, added in #9
